version: "3.2"

services:
  dev:
    container_name: substrate-polywrap-test-env
    image: ghcr.io/polywrap/integrations/substrate-polywrap-test-env:latest
    working_dir: /var/www/node-template
    ports:
      - "9944:9944"
      - "9933:9933"
    environment:
      - CARGO_HOME=/var/www/node-template/.cargo
    volumes:
      - .:/var/www/node-template
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "/node/node-template --dev --ws-external --rpc-external"
